/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as ApiAdminV1EntitlementsRouteImport } from './routes/api/admin/v1/entitlements'
import { Route as ApiAdminV1ReportsRouteImport } from './routes/api/admin/v1/reports'
import { Route as ApiAdminV1ReportsActionRouteImport } from './routes/api/admin/v1/reports-action'
import { Route as ApiAdminV1ReviewsRouteImport } from './routes/api/admin/v1/reviews'
import { Route as ApiAdminV1ReviewsActionRouteImport } from './routes/api/admin/v1/reviews-action'
import { Route as ApiPrivateV1CheckoutSessionRouteImport } from './routes/api/private/v1/checkout-session'
import { Route as ApiPrivateV1WebhooksStripeRouteImport } from './routes/api/private/v1/webhooks-stripe'
import { Route as ApiPublicV1ActiveSkinRouteImport } from './routes/api/public/v1/active-skin'
import { Route as ApiPublicV1CatalogRouteImport } from './routes/api/public/v1/catalog'
import { Route as ApiPublicV1MeRouteImport } from './routes/api/public/v1/me'
import { Route as ApiPublicV1PurchasesRouteImport } from './routes/api/public/v1/purchases'
import { Route as ApiPublicV1ReportRouteImport } from './routes/api/public/v1/report'
import { Route as ApiPublicV1SubmitRouteImport } from './routes/api/public/v1/submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const ApiAdminV1EntitlementsRoute = ApiAdminV1EntitlementsRouteImport.update({
  id: '/api/admin/v1/entitlements',
  path: '/api/admin/v1/entitlements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1ReportsRoute = ApiAdminV1ReportsRouteImport.update({
  id: '/api/admin/v1/reports',
  path: '/api/admin/v1/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1ReportsActionRoute = ApiAdminV1ReportsActionRouteImport.update({
  id: '/api/admin/v1/reports-action',
  path: '/api/admin/v1/reports-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1ReviewsRoute = ApiAdminV1ReviewsRouteImport.update({
  id: '/api/admin/v1/reviews',
  path: '/api/admin/v1/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1ReviewsActionRoute = ApiAdminV1ReviewsActionRouteImport.update({
  id: '/api/admin/v1/reviews-action',
  path: '/api/admin/v1/reviews-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateV1CheckoutSessionRoute =
  ApiPrivateV1CheckoutSessionRouteImport.update({
    id: '/api/private/v1/checkout-session',
    path: '/api/private/v1/checkout-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivateV1WebhooksStripeRoute =
  ApiPrivateV1WebhooksStripeRouteImport.update({
    id: '/api/private/v1/webhooks-stripe',
    path: '/api/private/v1/webhooks-stripe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ActiveSkinRoute = ApiPublicV1ActiveSkinRouteImport.update({
  id: '/api/public/v1/active-skin',
  path: '/api/public/v1/active-skin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CatalogRoute = ApiPublicV1CatalogRouteImport.update({
  id: '/api/public/v1/catalog',
  path: '/api/public/v1/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MeRoute = ApiPublicV1MeRouteImport.update({
  id: '/api/public/v1/me',
  path: '/api/public/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PurchasesRoute = ApiPublicV1PurchasesRouteImport.update({
  id: '/api/public/v1/purchases',
  path: '/api/public/v1/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ReportRoute = ApiPublicV1ReportRouteImport.update({
  id: '/api/public/v1/report',
  path: '/api/public/v1/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SubmitRoute = ApiPublicV1SubmitRouteImport.update({
  id: '/api/public/v1/submit',
  path: '/api/public/v1/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contribute': typeof ContributeRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/platforms': typeof PlatformsRoute
  '/seller': typeof SellerRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/api/admin/v1/entitlements': typeof ApiAdminV1EntitlementsRoute
  '/api/admin/v1/reports': typeof ApiAdminV1ReportsRoute
  '/api/admin/v1/reports-action': typeof ApiAdminV1ReportsActionRoute
  '/api/admin/v1/reviews': typeof ApiAdminV1ReviewsRoute
  '/api/admin/v1/reviews-action': typeof ApiAdminV1ReviewsActionRoute
  '/api/private/v1/checkout-session': typeof ApiPrivateV1CheckoutSessionRoute
  '/api/private/v1/webhooks-stripe': typeof ApiPrivateV1WebhooksStripeRoute
  '/api/public/v1/active-skin': typeof ApiPublicV1ActiveSkinRoute
  '/api/public/v1/catalog': typeof ApiPublicV1CatalogRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/purchases': typeof ApiPublicV1PurchasesRoute
  '/api/public/v1/report': typeof ApiPublicV1ReportRoute
  '/api/public/v1/submit': typeof ApiPublicV1SubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contribute': typeof ContributeRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/platforms': typeof PlatformsRoute
  '/seller': typeof SellerRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/api/admin/v1/entitlements': typeof ApiAdminV1EntitlementsRoute
  '/api/admin/v1/reports': typeof ApiAdminV1ReportsRoute
  '/api/admin/v1/reports-action': typeof ApiAdminV1ReportsActionRoute
  '/api/admin/v1/reviews': typeof ApiAdminV1ReviewsRoute
  '/api/admin/v1/reviews-action': typeof ApiAdminV1ReviewsActionRoute
  '/api/private/v1/checkout-session': typeof ApiPrivateV1CheckoutSessionRoute
  '/api/private/v1/webhooks-stripe': typeof ApiPrivateV1WebhooksStripeRoute
  '/api/public/v1/active-skin': typeof ApiPublicV1ActiveSkinRoute
  '/api/public/v1/catalog': typeof ApiPublicV1CatalogRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/purchases': typeof ApiPublicV1PurchasesRoute
  '/api/public/v1/report': typeof ApiPublicV1ReportRoute
  '/api/public/v1/submit': typeof ApiPublicV1SubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contribute': typeof ContributeRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/platforms': typeof PlatformsRoute
  '/seller': typeof SellerRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/api/admin/v1/entitlements': typeof ApiAdminV1EntitlementsRoute
  '/api/admin/v1/reports': typeof ApiAdminV1ReportsRoute
  '/api/admin/v1/reports-action': typeof ApiAdminV1ReportsActionRoute
  '/api/admin/v1/reviews': typeof ApiAdminV1ReviewsRoute
  '/api/admin/v1/reviews-action': typeof ApiAdminV1ReviewsActionRoute
  '/api/private/v1/checkout-session': typeof ApiPrivateV1CheckoutSessionRoute
  '/api/private/v1/webhooks-stripe': typeof ApiPrivateV1WebhooksStripeRoute
  '/api/public/v1/active-skin': typeof ApiPublicV1ActiveSkinRoute
  '/api/public/v1/catalog': typeof ApiPublicV1CatalogRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/purchases': typeof ApiPublicV1PurchasesRoute
  '/api/public/v1/report': typeof ApiPublicV1ReportRoute
  '/api/public/v1/submit': typeof ApiPublicV1SubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contribute'
    | '/docs'
    | '/download'
    | '/features'
    | '/legal'
    | '/library'
    | '/marketplace'
    | '/platforms'
    | '/seller'
    | '/setup'
    | '/sitemap.xml'
    | '/marketplace/$id'
    | '/api/admin/v1/entitlements'
    | '/api/admin/v1/reports'
    | '/api/admin/v1/reports-action'
    | '/api/admin/v1/reviews'
    | '/api/admin/v1/reviews-action'
    | '/api/private/v1/checkout-session'
    | '/api/private/v1/webhooks-stripe'
    | '/api/public/v1/active-skin'
    | '/api/public/v1/catalog'
    | '/api/public/v1/me'
    | '/api/public/v1/purchases'
    | '/api/public/v1/report'
    | '/api/public/v1/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contribute'
    | '/docs'
    | '/download'
    | '/features'
    | '/legal'
    | '/library'
    | '/marketplace'
    | '/platforms'
    | '/seller'
    | '/setup'
    | '/sitemap.xml'
    | '/marketplace/$id'
    | '/api/admin/v1/entitlements'
    | '/api/admin/v1/reports'
    | '/api/admin/v1/reports-action'
    | '/api/admin/v1/reviews'
    | '/api/admin/v1/reviews-action'
    | '/api/private/v1/checkout-session'
    | '/api/private/v1/webhooks-stripe'
    | '/api/public/v1/active-skin'
    | '/api/public/v1/catalog'
    | '/api/public/v1/me'
    | '/api/public/v1/purchases'
    | '/api/public/v1/report'
    | '/api/public/v1/submit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contribute'
    | '/docs'
    | '/download'
    | '/features'
    | '/legal'
    | '/library'
    | '/marketplace'
    | '/platforms'
    | '/seller'
    | '/setup'
    | '/sitemap.xml'
    | '/marketplace/$id'
    | '/api/admin/v1/entitlements'
    | '/api/admin/v1/reports'
    | '/api/admin/v1/reports-action'
    | '/api/admin/v1/reviews'
    | '/api/admin/v1/reviews-action'
    | '/api/private/v1/checkout-session'
    | '/api/private/v1/webhooks-stripe'
    | '/api/public/v1/active-skin'
    | '/api/public/v1/catalog'
    | '/api/public/v1/me'
    | '/api/public/v1/purchases'
    | '/api/public/v1/report'
    | '/api/public/v1/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContributeRoute: typeof ContributeRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  LegalRoute: typeof LegalRoute
  LibraryRoute: typeof LibraryRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  PlatformsRoute: typeof PlatformsRoute
  SellerRoute: typeof SellerRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdminV1EntitlementsRoute: typeof ApiAdminV1EntitlementsRoute
  ApiAdminV1ReportsRoute: typeof ApiAdminV1ReportsRoute
  ApiAdminV1ReportsActionRoute: typeof ApiAdminV1ReportsActionRoute
  ApiAdminV1ReviewsRoute: typeof ApiAdminV1ReviewsRoute
  ApiAdminV1ReviewsActionRoute: typeof ApiAdminV1ReviewsActionRoute
  ApiPrivateV1CheckoutSessionRoute: typeof ApiPrivateV1CheckoutSessionRoute
  ApiPrivateV1WebhooksStripeRoute: typeof ApiPrivateV1WebhooksStripeRoute
  ApiPublicV1ActiveSkinRoute: typeof ApiPublicV1ActiveSkinRoute
  ApiPublicV1CatalogRoute: typeof ApiPublicV1CatalogRoute
  ApiPublicV1MeRoute: typeof ApiPublicV1MeRoute
  ApiPublicV1PurchasesRoute: typeof ApiPublicV1PurchasesRoute
  ApiPublicV1ReportRoute: typeof ApiPublicV1ReportRoute
  ApiPublicV1SubmitRoute: typeof ApiPublicV1SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/api/admin/v1/entitlements': {
      id: '/api/admin/v1/entitlements'
      path: '/api/admin/v1/entitlements'
      fullPath: '/api/admin/v1/entitlements'
      preLoaderRoute: typeof ApiAdminV1EntitlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/reports': {
      id: '/api/admin/v1/reports'
      path: '/api/admin/v1/reports'
      fullPath: '/api/admin/v1/reports'
      preLoaderRoute: typeof ApiAdminV1ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/reports-action': {
      id: '/api/admin/v1/reports-action'
      path: '/api/admin/v1/reports-action'
      fullPath: '/api/admin/v1/reports-action'
      preLoaderRoute: typeof ApiAdminV1ReportsActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/reviews': {
      id: '/api/admin/v1/reviews'
      path: '/api/admin/v1/reviews'
      fullPath: '/api/admin/v1/reviews'
      preLoaderRoute: typeof ApiAdminV1ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/reviews-action': {
      id: '/api/admin/v1/reviews-action'
      path: '/api/admin/v1/reviews-action'
      fullPath: '/api/admin/v1/reviews-action'
      preLoaderRoute: typeof ApiAdminV1ReviewsActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/v1/checkout-session': {
      id: '/api/private/v1/checkout-session'
      path: '/api/private/v1/checkout-session'
      fullPath: '/api/private/v1/checkout-session'
      preLoaderRoute: typeof ApiPrivateV1CheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/v1/webhooks-stripe': {
      id: '/api/private/v1/webhooks-stripe'
      path: '/api/private/v1/webhooks-stripe'
      fullPath: '/api/private/v1/webhooks-stripe'
      preLoaderRoute: typeof ApiPrivateV1WebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/active-skin': {
      id: '/api/public/v1/active-skin'
      path: '/api/public/v1/active-skin'
      fullPath: '/api/public/v1/active-skin'
      preLoaderRoute: typeof ApiPublicV1ActiveSkinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/catalog': {
      id: '/api/public/v1/catalog'
      path: '/api/public/v1/catalog'
      fullPath: '/api/public/v1/catalog'
      preLoaderRoute: typeof ApiPublicV1CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/me': {
      id: '/api/public/v1/me'
      path: '/api/public/v1/me'
      fullPath: '/api/public/v1/me'
      preLoaderRoute: typeof ApiPublicV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/purchases': {
      id: '/api/public/v1/purchases'
      path: '/api/public/v1/purchases'
      fullPath: '/api/public/v1/purchases'
      preLoaderRoute: typeof ApiPublicV1PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/report': {
      id: '/api/public/v1/report'
      path: '/api/public/v1/report'
      fullPath: '/api/public/v1/report'
      preLoaderRoute: typeof ApiPublicV1ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/submit': {
      id: '/api/public/v1/submit'
      path: '/api/public/v1/submit'
      fullPath: '/api/public/v1/submit'
      preLoaderRoute: typeof ApiPublicV1SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContributeRoute: ContributeRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  LegalRoute: LegalRoute,
  LibraryRoute: LibraryRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  PlatformsRoute: PlatformsRoute,
  SellerRoute: SellerRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdminV1EntitlementsRoute: ApiAdminV1EntitlementsRoute,
  ApiAdminV1ReportsRoute: ApiAdminV1ReportsRoute,
  ApiAdminV1ReportsActionRoute: ApiAdminV1ReportsActionRoute,
  ApiAdminV1ReviewsRoute: ApiAdminV1ReviewsRoute,
  ApiAdminV1ReviewsActionRoute: ApiAdminV1ReviewsActionRoute,
  ApiPrivateV1CheckoutSessionRoute: ApiPrivateV1CheckoutSessionRoute,
  ApiPrivateV1WebhooksStripeRoute: ApiPrivateV1WebhooksStripeRoute,
  ApiPublicV1ActiveSkinRoute: ApiPublicV1ActiveSkinRoute,
  ApiPublicV1CatalogRoute: ApiPublicV1CatalogRoute,
  ApiPublicV1MeRoute: ApiPublicV1MeRoute,
  ApiPublicV1PurchasesRoute: ApiPublicV1PurchasesRoute,
  ApiPublicV1ReportRoute: ApiPublicV1ReportRoute,
  ApiPublicV1SubmitRoute: ApiPublicV1SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
