package com.kurostream.tv.domain.model

import kotlinx.serialization.Serializable

/**
 * Domain model representing an Episode.
 * 
 * Contains all information needed to display and play an episode.
 */
@Serializable
data class Episode(
    val id: String,
    val animeId: String,
    val number: Int,
    val title: String? = null,
    val titleEnglish: String? = null,
    val titleJapanese: String? = null,
    val synopsis: String? = null,
    val thumbnail: String? = null,
    val duration: Int? = null, // in minutes
    val airDate: String? = null, // ISO date format
    val isFiller: Boolean = false,
    val isRecap: Boolean = false,
    val streamSources: List<StreamSource> = emptyList(),
    val subtitles: List<Subtitle> = emptyList(),
    val skipTimestamps: SkipTimestamps? = null,
    val watchPosition: Long = 0L, // last watched position in milliseconds
    val isWatched: Boolean = false,
    val watchedAt: Long? = null // timestamp when marked as watched
) {
    /**
     * Returns the display title with episode number.
     */
    fun getDisplayTitle(preferEnglish: Boolean = true): String {
        val episodeTitle = if (preferEnglish) {
            titleEnglish ?: title
        } else {
            title ?: titleEnglish
        }
        return episodeTitle?.let { "Episode $number: $it" } ?: "Episode $number"
    }

    /**
     * Returns the short display title.
     */
    val shortTitle: String
        get() = "Ep. $number"

    /**
     * Returns true if the episode has playable sources.
     */
    val hasStreams: Boolean
        get() = streamSources.isNotEmpty()

    /**
     * Returns the best quality stream source.
     */
    val bestQualitySource: StreamSource?
        get() = streamSources.maxByOrNull { it.quality.ordinal }

    /**
     * Returns the watch progress percentage.
     */
    val watchProgressPercentage: Float
        get() {
            val durationMs = (duration ?: 24) * 60 * 1000L
            return (watchPosition.toFloat() / durationMs.toFloat()) * 100f
        }

    /**
     * Returns true if episode is partially watched (>2% and <90%).
     */
    val isPartiallyWatched: Boolean
        get() = watchProgressPercentage > 2f && watchProgressPercentage < 90f
}

/**
 * Stream source for an episode.
 */
@Serializable
data class StreamSource(
    val id: String,
    val url: String,
    val provider: String,
    val quality: StreamQuality = StreamQuality.AUTO,
    val type: StreamType = StreamType.DIRECT,
    val headers: Map<String, String> = emptyMap(),
    val isWorking: Boolean = true,
    val isDub: Boolean = false,
    val language: String = "ja" // ISO 639-1 code
) {
    /**
     * Returns true if this is a torrent/magnet source.
     */
    val isTorrent: Boolean
        get() = type == StreamType.TORRENT || url.startsWith("magnet:")
}

/**
 * Video stream quality levels.
 */
@Serializable
enum class StreamQuality(val resolution: Int) {
    P360(360),
    P480(480),
    P720(720),
    P1080(1080),
    P1440(1440),
    P2160(2160),
    AUTO(0);

    companion object {
        fun fromResolution(height: Int): StreamQuality {
            return entries.filter { it != AUTO }
                .minByOrNull { kotlin.math.abs(it.resolution - height) }
                ?: AUTO
        }
    }
}

/**
 * Type of stream source.
 */
@Serializable
enum class StreamType {
    DIRECT,     // Direct video URL
    HLS,        // HLS manifest
    DASH,       // DASH manifest
    TORRENT,    // Torrent/Magnet link
    EMBED       // Embedded player URL
}

/**
 * Subtitle track for an episode.
 */
@Serializable
data class Subtitle(
    val id: String,
    val url: String,
    val language: String, // ISO 639-1 code
    val languageName: String, // Display name
    val format: SubtitleFormat = SubtitleFormat.SRT,
    val isDefault: Boolean = false,
    val isAutoGenerated: Boolean = false
)

/**
 * Subtitle file format.
 */
@Serializable
enum class SubtitleFormat(val extension: String) {
    SRT("srt"),
    ASS("ass"),
    SSA("ssa"),
    VTT("vtt"),
    SUB("sub"),
    TTML("ttml")
}

/**
 * Skip timestamps for opening/ending/recap.
 */
@Serializable
data class SkipTimestamps(
    val opening: TimeRange? = null,
    val ending: TimeRange? = null,
    val recap: TimeRange? = null,
    val preview: TimeRange? = null,
    val mixedOpening: TimeRange? = null,
    val mixedEnding: TimeRange? = null
)

/**
 * Time range in milliseconds.
 */
@Serializable
data class TimeRange(
    val startMs: Long,
    val endMs: Long
) {
    /**
     * Returns true if the given position is within this range.
     */
    fun contains(positionMs: Long): Boolean {
        return positionMs in startMs..endMs
    }

    /**
     * Returns the duration in milliseconds.
     */
    val durationMs: Long
        get() = endMs - startMs

    /**
     * Returns the duration formatted as MM:SS.
     */
    val formattedDuration: String
        get() {
            val seconds = durationMs / 1000
            val mins = seconds / 60
            val secs = seconds % 60
            return "%d:%02d".format(mins, secs)
        }
}

/**
 * Episode with additional metadata for display.
 */
@Serializable
data class EpisodeWithMetadata(
    val episode: Episode,
    val animeTitle: String,
    val animeCoverImage: String?,
    val nextEpisode: Episode? = null,
    val previousEpisode: Episode? = null
)
