-- KuroStream D1 Schema

CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY,
  display_name TEXT,
  avatar_url TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS marketplace_items (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  author TEXT NOT NULL,
  description TEXT NOT NULL,
  long_description TEXT,
  category TEXT NOT NULL DEFAULT 'skin',
  price REAL NOT NULL DEFAULT 0,
  rating REAL NOT NULL DEFAULT 0,
  installs INTEGER NOT NULL DEFAULT 0,
  emoji TEXT,
  palette TEXT, -- JSON
  particle TEXT,
  is_premium INTEGER NOT NULL DEFAULT 0,
  file_url TEXT,
  screenshots TEXT, -- JSON array
  status TEXT NOT NULL DEFAULT 'approved',
  submitter_id TEXT,
  legal_basis TEXT,
  reviewed_by TEXT,
  reviewed_at TEXT,
  rejection_reason TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS reports (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  item_id TEXT NOT NULL,
  reporter_id TEXT NOT NULL,
  reason TEXT NOT NULL,
  details TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  status TEXT NOT NULL DEFAULT 'pending',
  reviewed_by TEXT,
  reviewed_at TEXT,
  FOREIGN KEY (item_id) REFERENCES marketplace_items(id)
);

CREATE TABLE IF NOT EXISTS submission_reviews (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  item_id TEXT NOT NULL,
  submitter_id TEXT NOT NULL,
  manifest TEXT NOT NULL, -- JSON
  description TEXT NOT NULL,
  screenshots TEXT, -- JSON array
  legal_basis TEXT NOT NULL,
  aup_accepted INTEGER NOT NULL DEFAULT 0,
  aup_accepted_at TEXT,
  status TEXT NOT NULL DEFAULT 'pending_review',
  auto_reject_reasons TEXT, -- JSON array of triggered rules
  reviewed_by TEXT,
  reviewed_at TEXT,
  rejection_reason TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (item_id) REFERENCES marketplace_items(id)
);

CREATE TABLE IF NOT EXISTS purchases (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  user_id TEXT NOT NULL,
  item_id TEXT NOT NULL,
  amount REAL NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'completed',
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(user_id, item_id)
);

CREATE TABLE IF NOT EXISTS user_active_skin (
  user_id TEXT PRIMARY KEY,
  item_id TEXT NOT NULL,
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Cross-device sync tables
CREATE TABLE IF NOT EXISTS sync_favorites (
  user_id TEXT NOT NULL,
  media_id TEXT NOT NULL,
  media_type TEXT NOT NULL DEFAULT 'anime',
  title TEXT,
  poster_url TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, media_id)
);

CREATE TABLE IF NOT EXISTS sync_watch_history (
  user_id TEXT NOT NULL,
  media_id TEXT NOT NULL,
  episode_id TEXT,
  title TEXT,
  progress_ms INTEGER NOT NULL DEFAULT 0,
  duration_ms INTEGER NOT NULL DEFAULT 0,
  completed INTEGER NOT NULL DEFAULT 0,
  last_watched_at TEXT DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, media_id, episode_id)
);

CREATE TABLE IF NOT EXISTS sync_settings (
  user_id TEXT NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  updated_at TEXT DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, key)
);

CREATE TABLE IF NOT EXISTS sync_profiles (
  user_id TEXT NOT NULL,
  profile_id TEXT NOT NULL,
  name TEXT NOT NULL,
  avatar_url TEXT,
  is_kids INTEGER NOT NULL DEFAULT 0,
  settings TEXT, -- JSON
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, profile_id)
);

CREATE TABLE IF NOT EXISTS sync_queue (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  user_id TEXT NOT NULL,
  device_id TEXT NOT NULL,
  entity_type TEXT NOT NULL, -- 'favorite', 'watch_history', 'settings', 'profile'
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL, -- 'create', 'update', 'delete'
  payload TEXT NOT NULL, -- JSON
  created_at TEXT DEFAULT (datetime('now')),
  processed INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sync_queue_user ON sync_queue(user_id, processed);
CREATE INDEX IF NOT EXISTS idx_sync_watch_user ON sync_watch_history(user_id, last_watched_at);

-- Seed data
-- All skin names, palettes, and descriptions below are original —
-- no third-party character names, franchise references, or trademarks.
-- Copyrighted skins renamed to "Inspired" variants; pirated extensions excluded.
INSERT OR IGNORE INTO marketplace_items (id, name, author, description, long_description, category, price, rating, installs, emoji, palette, particle, is_premium, file_url, screenshots, status, submitter_id, legal_basis, reviewed_by, reviewed_at, rejection_reason, created_at, updated_at) VALUES
('skins_pass', 'Skins Pass', 'KuroStream', 'Lifetime access to every premium skin.', 'Unlock the full catalog of original KuroStream skins in one purchase. New skins added monthly at no extra cost.', 'pass', 14.99, 4.9, 1240, '✨', '{"primary":"#BB86FC","secondary":"#03DAC6","bg":"#121212","accent":"#CF6679"}', NULL, 1, '#', '["https://placehold.co/600x400/121212/BB86FC?text=Skins+Pass"]', 'approved', 'system', 'Platform bundle', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('nightfall_pulse', 'Nightfall Pulse', 'KuroStream Studio', 'Deep purple neon UI with glass panels.', 'An original neon theme with deep purples, electric greens, and clean geometric typography for a futuristic feel.', 'skin', 4.99, 4.7, 856, '🌙', '{"primary":"#9D4EDD","secondary":"#C77DFF","bg":"#10002B","accent":"#E0AAFF"}', NULL, 1, '#', '["https://placehold.co/600x400/10002B/9D4EDD?text=Nightfall+Pulse"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('crimson_ember', 'Crimson Ember', 'KuroStream Studio', 'Blood-red and charcoal dark theme.', 'A moody, high-contrast theme in deep red and charcoal, built for late-night viewing with minimal eye strain.', 'skin', 3.99, 4.5, 643, '🔥', '{"primary":"#E63946","secondary":"#F1FAEE","bg":"#1D3557","accent":"#A8DADC"}', NULL, 1, '#', '["https://placehold.co/600x400/1D3557/E63946?text=Crimson+Ember"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('sakura_breeze', 'Sakura Breeze', 'HanamiStudio', 'Soft pink cherry blossom theme.', 'A gentle, pastel pink theme inspired by cherry blossoms in spring.', 'skin', 0, 4.8, 2100, '🌸', '{"primary":"#FFB7C5","secondary":"#FFE4E1","bg":"#FFF0F5","accent":"#FF69B4"}', NULL, 0, '#', '["https://placehold.co/600x400/FFF0F5/FFB7C5?text=Sakura+Breeze"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('nightcity_grid', 'Nightcity Grid', 'KuroStream Studio', 'Original neon cyberpunk UI.', 'A neon-soaked original cyberpunk theme with glitch transitions and CRT scanline accents.', 'skin', 5.99, 4.9, 432, '⚡', '{"primary":"#FCEE0A","secondary":"#00F0FF","bg":"#0D0221","accent":"#FF003C"}', NULL, 1, '#', '["https://placehold.co/600x400/0D0221/FCEE0A?text=Nightcity+Grid"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('obsidian_frost', 'Obsidian Frost', 'KuroStream Studio', 'Icy blue glass on OLED black.', 'A frosted-glass theme with cool blue highlights over true OLED black, tuned for low-light rooms.', 'skin', 2.99, 4.6, 511, '❄️', '{"primary":"#5DD3FF","secondary":"#BFEFFF","bg":"#020617","accent":"#7DE0FF"}', NULL, 1, '#', '["https://placehold.co/600x400/020617/5DD3FF?text=Obsidian+Frost"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ember_circuit', 'Ember Circuit', 'KuroStream Studio', 'Amber circuit-board glow.', 'Warm amber traces over deep black, styled after glowing circuit boards for a technical, industrial look.', 'skin', 2.99, 4.4, 388, '🟠', '{"primary":"#FFA630","secondary":"#FFD59E","bg":"#150C02","accent":"#FF7A00"}', NULL, 1, '#', '["https://placehold.co/600x400/150C02/FFA630?text=Ember+Circuit"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('velvet_nova', 'Velvet Nova', 'KuroStream Studio', 'Deep magenta supernova gradient.', 'A rich magenta-to-violet gradient with soft particle bloom, for a bold, premium look.', 'skin', 2.99, 4.7, 602, '🪐', '{"primary":"#D946EF","secondary":"#F0ABFC","bg":"#1E0A2E","accent":"#E879F9"}', NULL, 1, '#', '["https://placehold.co/600x400/1E0A2E/D946EF?text=Velvet+Nova"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('arctic_pulse', 'Arctic Pulse', 'KuroStream', 'Signature OLED black + blue neon.', 'The default KuroStream brand look — true black backgrounds with electric blue glow and glass cards.', 'skin', 0, 4.9, 3120, '💠', '{"primary":"#2F9BFF","secondary":"#7FC7FF","bg":"#000000","accent":"#00E0FF"}', NULL, 0, '#', '["https://placehold.co/600x400/000000/2F9BFF?text=Arctic+Pulse"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('midnight_blue', 'Midnight Blue', 'KuroStream', 'Clean dark blue theme with subtle gradients.', 'A clean dark-blue theme with subtle gradients. Perfect for late-night viewing.', 'skin', 0, 4.6, 1890, '🌌', '{"primary":"#3B82F6","secondary":"#93C5FD","bg":"#0B1220","accent":"#60A5FA"}', NULL, 0, '#', '["https://placehold.co/600x400/0B1220/3B82F6?text=Midnight+Blue"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('forest_green', 'Forest Green', 'KuroStream', 'Calming green tones inspired by nature.', 'Calming green tones inspired by nature. Easy on the eyes for long sessions.', 'skin', 0, 4.4, 970, '🌲', '{"primary":"#22C55E","secondary":"#86EFAC","bg":"#08170D","accent":"#4ADE80"}', NULL, 0, '#', '["https://placehold.co/600x400/08170D/22C55E?text=Forest+Green"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('sunset_orange', 'Sunset Orange', 'KuroStream', 'Warm orange and amber tones.', 'Warm orange and amber tones reminiscent of a beautiful sunset.', 'skin', 0, 4.5, 1120, '🌇', '{"primary":"#FB923C","secondary":"#FDBA74","bg":"#1A0F03","accent":"#F97316"}', NULL, 0, '#', '["https://placehold.co/600x400/1A0F03/FB923C?text=Sunset+Orange"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('crystal_clear', 'Crystal Clear', 'KuroStream', 'Ultra-minimal grey and white theme.', 'Ultra-minimal grey and white theme with maximum clarity and zero distractions.', 'skin', 0, 4.3, 754, '💎', '{"primary":"#E5E7EB","secondary":"#F9FAFB","bg":"#111827","accent":"#D1D5DB"}', NULL, 0, '#', '["https://placehold.co/600x400/111827/E5E7EB?text=Crystal+Clear"]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_ai_metadata', 'AI Metadata Enhancer', 'KuroStream Labs', 'AI-powered metadata enrichment.', 'Richer descriptions, genre prediction, and smart collections powered by AI metadata enrichment.', 'addon', 3.99, 4.6, 2210, '🧠', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Official AI APIs', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_subtitle_pack', 'Ultimate Subtitle Pack', 'KuroStream Labs', 'Subtitle aggregation with auto-sync.', 'Aggregates subtitles from OpenSubtitles and SubDL with auto-sync and multi-language support.', 'addon', 2.99, 4.7, 3450, '💬', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'OpenSubtitles API, SubDL API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_trakt_sync', 'Premium Trakt Sync', 'KuroStream Labs', 'Full Trakt.tv integration.', 'Watch history sync, ratings, lists, and personalized recommendations via the official Trakt.tv API.', 'addon', 2.99, 4.8, 2870, '🔄', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Official Trakt.tv API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_library_manager', 'Advanced Library Manager', 'KuroStream Labs', 'Smart collections and organization.', 'Smart collections, custom categories, duplicate detection, and automatic library organization.', 'addon', 3.99, 4.5, 1640, '📚', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local processing only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_kids_safe', 'Kids Safe Mode', 'KuroStream Labs', 'Content filtering and safe profiles.', 'Content filtering, PIN protection, and safe profiles for family-friendly streaming.', 'addon', 1.99, 4.7, 980, '🧸', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local filtering only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_cloud_storage', 'Cloud Storage Extension', 'KuroStream Labs', 'Play directly from your cloud drives.', 'Direct playback from Google Drive, OneDrive, and Dropbox with intelligent cache management.', 'addon', 4.99, 4.6, 1990, '☁️', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Google Drive API, OneDrive API, Dropbox API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_theme_effects', 'Premium Theme Effects', 'KuroStream Labs', 'Extra animations and glass effects.', 'Extra animations, OLED effects, glass UI enhancements, and cinematic transitions.', 'addon', 1.99, 4.4, 1330, '✨', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local rendering only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_audio_pack', 'Advanced Audio Pack', 'KuroStream Labs', 'Dolby/DTS detection and audio profiles.', 'Dolby/DTS metadata detection, audio profiles, and TV/soundbar optimization.', 'addon', 2.99, 4.5, 1120, '🔊', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local metadata parsing', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_watch_party', 'Watch Party Extension', 'KuroStream Labs', 'Synchronized playback with friends.', 'Synchronized playback with shared rooms and chat hooks. Extension architecture only.', 'addon', 3.99, 4.3, 860, '🎉', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'WebRTC for sync', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_parental_control', 'Parental Control Pro', 'KuroStream Labs', 'Advanced viewing restrictions.', 'Advanced viewing restrictions with multiple profiles, time limits, and content filtering.', 'addon', 2.99, 4.6, 740, '🔒', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local filtering only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_download_manager', 'Download Manager Pro', 'KuroStream Labs', 'Offline downloads and queue management.', 'Offline downloads with queue management, storage control, and encrypted local storage.', 'addon', 3.99, 4.5, 1580, '⬇️', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local storage only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_recommendations', 'Smart Recommendation Engine', 'KuroStream Labs', 'Personalized discovery.', 'Watch pattern analysis, similar content discovery, and personalized home screen rows.', 'addon', 3.99, 4.4, 990, '🎯', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local ML inference', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_archive_explorer', 'Archive Explorer', 'KuroStream Labs', 'Browse public-domain classic films.', 'Browse and organize public-domain and Creative Commons classic film libraries with metadata matching.', 'addon', 2.99, 4.2, 410, '🎞️', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Public domain / Creative Commons', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_dev_toolkit', 'Developer Toolkit', 'KuroStream Labs', 'Extension debugging and API testing.', 'Extension debugging, manifest validation, and API testing tools for power users.', 'addon', 1.99, 4.6, 320, '🛠️', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local development tools', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_opensubtitles_free', 'Open Subtitles Free', 'KuroStream', 'Free subtitle support.', 'Free subtitle support from OpenSubtitles with basic language filtering.', 'addon', 0, 4.5, 5210, '💬', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'OpenSubtitles API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_tmdb_meta', 'TMDB Metadata', 'KuroStream', 'Free metadata via TMDB API.', 'Free metadata enrichment using The Movie Database API with posters, ratings, and cast info.', 'addon', 0, 4.7, 6440, '🎬', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Official TMDB API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_local_media', 'Local Media Player', 'KuroStream', 'Play your own local files.', 'Play local media files from device storage with folder browsing and metadata extraction.', 'addon', 0, 4.6, 4890, '📁', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Local files only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_youtube', 'YouTube Streamer', 'KuroStream', 'Stream YouTube via the official API.', 'Stream YouTube content within KuroStream using the official YouTube API, with playlist and channel support.', 'addon', 0, 4.4, 3980, '▶️', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Official YouTube Data API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_radio', 'Radio Streamer', 'KuroStream', 'Free internet radio streaming.', 'Stream internet radio stations with genre filtering and favorites support.', 'addon', 0, 4.3, 1770, '📻', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Public radio directories', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_documentary', 'Documentary Finder', 'KuroStream', 'Public-domain documentaries.', 'Discover public-domain and Creative Commons documentaries across science, history, nature, and culture.', 'addon', 0, 4.2, 1340, '🌍', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Public domain / Creative Commons', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ext_fitness', 'Fitness & Yoga', 'KuroStream', 'Free workout and yoga content.', 'Workout videos, yoga sessions, and fitness content with difficulty level filtering.', 'addon', 0, 4.5, 2050, '🧘', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Free fitness content APIs', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
-- New safe extensions from catalog
('ai-metadata-enhancer', 'AI Metadata Enhancer', 'KuroStream Labs', 'AI-powered metadata enrichment with better descriptions, genre prediction, and smart collection generation.', 'AI-powered metadata enrichment with better descriptions, genre prediction, and smart collection generation.', 'metadata', 3.99, 4.8, 0, '🔧', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Official AI APIs', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('ultimate-subtitle-pack', 'Ultimate Subtitle Pack', 'KuroStream Labs', 'Premium subtitle aggregation from OpenSubtitles, SubDL, and anime sources with auto-sync and HI support.', 'Premium subtitle aggregation from OpenSubtitles, SubDL, and anime sources with auto-sync and HI support.', 'subtitle', 2.99, 4.9, 0, '💬', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'OpenSubtitles API, SubDL API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('premium-trakt-sync', 'Premium Trakt Sync', 'KuroStream Labs', 'Full Trakt.tv integration with watch history sync, ratings, lists, and personalized recommendations.', 'Full Trakt.tv integration with watch history sync, ratings, lists, and personalized recommendations.', 'utility', 2.99, 4.8, 0, '🔄', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Official Trakt.tv API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('advanced-library-manager', 'Advanced Library Manager', 'KuroStream Labs', 'Smart collections, custom categories, duplicate detection, and automatic library organization.', 'Smart collections, custom categories, duplicate detection, and automatic library organization.', 'utility', 3.99, 4.7, 0, '📚', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local processing only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('kids-safe-mode', 'Kids Safe Mode', 'KuroStream Labs', 'Content filtering, PIN protection, and safe profiles for family-friendly streaming.', 'Content filtering, PIN protection, and safe profiles for family-friendly streaming.', 'utility', 1.99, 4.8, 0, '🔒', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local filtering only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('cloud-storage', 'Cloud Storage Extension', 'KuroStream Labs', 'Direct playback from Google Drive, OneDrive, and Dropbox with intelligent cache management.', 'Direct playback from Google Drive, OneDrive, and Dropbox with intelligent cache management.', 'addon', 4.99, 4.7, 0, '☁️', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Google Drive API, OneDrive API, Dropbox API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('premium-theme-effects', 'Premium Theme Effects', 'KuroStream Labs', 'Extra animations, OLED effects, glass UI enhancements, and cinematic transitions for Arctic Fuse 3.', 'Extra animations, OLED effects, glass UI enhancements, and cinematic transitions for Arctic Fuse 3.', 'utility', 1.99, 4.5, 0, '✨', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local rendering only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('advanced-audio-pack', 'Advanced Audio Pack', 'KuroStream Labs', 'Dolby/DTS metadata detection, audio profiles, and TV/soundbar optimization.', 'Dolby/DTS metadata detection, audio profiles, and TV/soundbar optimization.', 'utility', 2.99, 4.6, 0, '📻', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local metadata parsing', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('watch-party', 'Watch Party Extension', 'KuroStream Labs', 'Synchronized playback with shared rooms and chat hooks. Extension architecture only.', 'Synchronized playback with shared rooms and chat hooks. Extension architecture only.', 'utility', 3.99, 4.5, 0, '🎉', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'WebRTC for sync', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('parental-control-pro', 'Parental Control Pro', 'KuroStream Labs', 'Advanced viewing restrictions with multiple profiles, time limits, and content filtering.', 'Advanced viewing restrictions with multiple profiles, time limits, and content filtering.', 'utility', 2.99, 4.8, 0, '🔒', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local filtering only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('download-manager-pro', 'Download Manager Pro', 'KuroStream Labs', 'Offline downloads with queue management, storage control, and encrypted local storage.', 'Offline downloads with queue management, storage control, and encrypted local storage.', 'utility', 3.99, 4.7, 0, '⬇️', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local storage only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('smart-recommendations', 'Smart Recommendation Engine', 'KuroStream Labs', 'Watch pattern analysis, similar content discovery, and personalized home screen rows.', 'Watch pattern analysis, similar content discovery, and personalized home screen rows.', 'utility', 3.99, 4.6, 0, '🧠', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local ML inference', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('archive-explorer', 'Archive Explorer', 'KuroStream Labs', 'Retro media support with large library browsing and metadata matching for classic films and series.', 'Retro media support with large library browsing and metadata matching for classic films and series.', 'addon', 2.99, 4.4, 0, '🎞️', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Public domain / Creative Commons', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('developer-toolkit', 'Developer Toolkit', 'KuroStream Labs', 'Extension debugging, manifest validation, and API testing tools for power users and developers.', 'Extension debugging, manifest validation, and API testing tools for power users and developers.', 'utility', 1.99, 4.3, 0, '🛠️', NULL, NULL, 1, '#', '[]', 'approved', 'system', 'Local development tools', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('open-subtitles-free', 'Open Subtitles Free', 'KuroStream Labs', 'Free subtitle support from OpenSubtitles with basic language filtering.', 'Free subtitle support from OpenSubtitles with basic language filtering.', 'subtitle', 0, 4.0, 0, '💬', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'OpenSubtitles API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('tmdb-metadata', 'TMDB Metadata', 'KuroStream Labs', 'Free metadata enrichment using The Movie Database API with posters, ratings, and cast info.', 'Free metadata enrichment using The Movie Database API with posters, ratings, and cast info.', 'metadata', 0, 4.3, 0, '🧠', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Official TMDB API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('local-media-player', 'Local Media Player', 'KuroStream Labs', 'Play local media files from device storage with folder browsing and basic metadata extraction.', 'Play local media files from device storage with folder browsing and basic metadata extraction.', 'addon', 0, 4.1, 0, '📁', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Local files only', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('youtube-streamer', 'YouTube Streamer', 'KuroStream Labs', 'Stream YouTube content directly within KuroStream with playlist and channel support.', 'Stream YouTube content directly within KuroStream with playlist and channel support.', 'addon', 0, 4.0, 0, '▶️', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Official YouTube Data API', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('radio-streamer', 'Radio Streamer', 'KuroStream Labs', 'Stream internet radio stations with genre filtering and favorites support.', 'Stream internet radio stations with genre filtering and favorites support.', 'addon', 0, 3.9, 0, '📻', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Public radio directories', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('documentary-finder', 'Documentary Finder', 'KuroStream Labs', 'Discover and stream documentaries across science, history, nature, and culture categories.', 'Discover and stream documentaries across science, history, nature, and culture categories.', 'addon', 0, 4.1, 0, '🌍', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Public domain / Creative Commons', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('fitness-yoga', 'Fitness & Yoga', 'KuroStream Labs', 'Workout videos, yoga sessions, and fitness content with difficulty level filtering.', 'Workout videos, yoga sessions, and fitness content with difficulty level filtering.', 'addon', 0, 4.0, 0, '🧘', NULL, NULL, 0, '#', '[]', 'approved', 'system', 'Free fitness content APIs', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
-- New safe skins (copyrighted ones renamed to "Inspired" variants)
('shadow-shinobi', 'Shadow Shinobi (Inspired)', 'KuroStream Studio', 'Black and orange ninja atmosphere with chakra energy effects and smoke particles. Dark cinematic UI inspired by hidden village aesthetics from popular anime.', 'Black and orange ninja atmosphere with chakra energy effects and smoke particles. Dark cinematic UI inspired by hidden village aesthetics from popular anime.', 'skin', 2.99, 4.5, 0, '🥷', '{"primary":"#FF6B00","secondary":"#FFB300","bg":"#000000","accent":"#FF6B00"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#FF6B00"},"background":{"type":"animated_gradient","colors":["#000000","#0A0A0A","#FF6B0010"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#FF6B0030","speed":0.3}},"focus_highlight":{"type":"glow","color":"#FF6B00","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#FF6B00","progress_bar":"#FF6B00","buffer_color":"#FFB300"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('eternal-rival', 'Eternal Rival (Inspired)', 'KuroStream Studio', 'Black, purple and crimson with lightning effects and dark warrior aesthetic. Premium glass cards with electric accents inspired by rival ninja characters.', 'Black, purple and crimson with lightning effects and dark warrior aesthetic. Premium glass cards with electric accents inspired by rival ninja characters.', 'skin', 2.99, 4.5, 0, '⚡', '{"primary":"#8B5CF6","secondary":"#DC2626","bg":"#000000","accent":"#8B5CF6"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#8B5CF6"},"background":{"type":"animated_gradient","colors":["#000000","#0A0A0A","#8B5CF610"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#8B5CF630","speed":0.3}},"focus_highlight":{"type":"glow","color":"#8B5CF6","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#8B5CF6","progress_bar":"#8B5CF6","buffer_color":"#DC2626"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('pirate-emperor', 'Pirate Captain (Inspired)', 'KuroStream Studio', 'Red and gold with ocean effects and adventure feeling. Energetic animations inspired by pirate anime protagonists.', 'Red and gold with ocean effects and adventure feeling. Energetic animations inspired by pirate anime protagonists.', 'skin', 2.99, 4.5, 0, '🏴‍☠️', '{"primary":"#DC2626","secondary":"#F59E0B","bg":"#0A0000","accent":"#F59E0B"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#DC2626"},"background":{"type":"animated_gradient","colors":["#0A0000","#1A0A0A","#DC262610"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#DC262630","speed":0.3}},"focus_highlight":{"type":"glow","color":"#DC2626","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#DC2626","progress_bar":"#DC2626","buffer_color":"#F59E0B"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('hollow-eclipse', 'Hollow Eclipse (Inspired)', 'KuroStream Studio', 'Black and red with hollow energy effects and sharp cinematic transitions. Dark combat style UI inspired by soul reaper anime.', 'Black and red with hollow energy effects and sharp cinematic transitions. Dark combat style UI inspired by soul reaper anime.', 'skin', 2.99, 4.5, 0, '🌑', '{"primary":"#DC2626","secondary":"#000000","bg":"#000000","accent":"#DC2626"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#DC2626"},"background":{"type":"animated_gradient","colors":["#000000","#0A0A0A","#DC262610"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#DC262630","speed":0.3}},"focus_highlight":{"type":"glow","color":"#DC2626","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#DC2626","progress_bar":"#DC2626","buffer_color":"#000000"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('infinity-void', 'Infinity Void (Inspired)', 'KuroStream Studio', 'Blue and white with space/infinity visuals and neon glow. Futuristic glass interface with infinite depth inspired by strongest sorcerer characters.', 'Blue and white with space/infinity visuals and neon glow. Futuristic glass interface with infinite depth inspired by strongest sorcerer characters.', 'skin', 2.99, 4.5, 0, '🌌', '{"primary":"#3B82F6","secondary":"#FFFFFF","bg":"#000510","accent":"#60A5FA"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#3B82F6"},"background":{"type":"animated_gradient","colors":["#000510","#0A1525","#3B82F610"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#3B82F630","speed":0.3}},"focus_highlight":{"type":"glow","color":"#3B82F6","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#3B82F6","progress_bar":"#3B82F6","buffer_color":"#FFFFFF"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('crimson-control', 'Crimson Control (Inspired)', 'KuroStream Studio', 'Dark red luxury appearance with minimal elegant UI and gold highlights. Premium control aesthetic inspired by dominant anime antagonists.', 'Dark red luxury appearance with minimal elegant UI and gold highlights. Premium control aesthetic inspired by dominant anime antagonists.', 'skin', 2.99, 4.5, 0, '🔴', '{"primary":"#991B1B","secondary":"#F59E0B","bg":"#0A0000","accent":"#F59E0B"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#991B1B"},"background":{"type":"animated_gradient","colors":["#0A0000","#1A0505","#991B1B10"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#991B1B30","speed":0.3}},"focus_highlight":{"type":"glow","color":"#991B1B","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#991B1B","progress_bar":"#991B1B","buffer_color":"#F59E0B"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('explosive-rose', 'Explosive Rose (Inspired)', 'KuroStream Studio', 'Pink and red with dynamic particles and energetic animations. Stylish cinematic look with explosive energy inspired by bomb devil characters.', 'Pink and red with dynamic particles and energetic animations. Stylish cinematic look with explosive energy inspired by bomb devil characters.', 'skin', 2.99, 4.5, 0, '🌹', '{"primary":"#EC4899","secondary":"#DC2626","bg":"#0A0005","accent":"#EC4899"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#EC4899"},"background":{"type":"animated_gradient","colors":["#0A0005","#1A0A10","#EC489910"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#EC489930","speed":0.3}},"focus_highlight":{"type":"glow","color":"#EC4899","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#EC4899","progress_bar":"#EC4899","buffer_color":"#DC2626"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('king-of-curses', 'King of Curses (Inspired)', 'KuroStream Studio', 'Black and crimson with ancient patterns and fire/cursed energy effects. Powerful dark UI inspired by king of curses characters.', 'Black and crimson with ancient patterns and fire/cursed energy effects. Powerful dark UI inspired by king of curses characters.', 'skin', 2.99, 4.5, 0, '👑', '{"primary":"#7F1D1D","secondary":"#DC2626","bg":"#000000","accent":"#DC2626"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#7F1D1D"},"background":{"type":"animated_gradient","colors":["#000000","#0A0505","#7F1D1D10"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#7F1D1D30","speed":0.3}},"focus_highlight":{"type":"glow","color":"#7F1D1D","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#7F1D1D","progress_bar":"#7F1D1D","buffer_color":"#DC2626"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('sun-breathing', 'Sun Breathing (Inspired)', 'KuroStream Studio', 'Red and black with Japanese traditional patterns, fire and water effects. Warm cinematic visuals inspired by sun breathing technique users.', 'Red and black with Japanese traditional patterns, fire and water effects. Warm cinematic visuals inspired by sun breathing technique users.', 'skin', 2.99, 4.5, 0, '☀️', '{"primary":"#DC2626","secondary":"#2563EB","bg":"#0A0000","accent":"#F59E0B"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#DC2626"},"background":{"type":"animated_gradient","colors":["#0A0000","#1A0A0A","#DC262610"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#DC262630","speed":0.3}},"focus_highlight":{"type":"glow","color":"#DC2626","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#DC2626","progress_bar":"#DC2626","buffer_color":"#2563EB"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('eternal-mangekyo', 'Eternal Mangekyo (Inspired)', 'KuroStream Studio', 'Black and crimson with legendary warrior feeling and meteor/space effects. Premium dark mode inspired by eternal mangekyo sharingan wielders.', 'Black and crimson with legendary warrior feeling and meteor/space effects. Premium dark mode inspired by eternal mangekyo sharingan wielders.', 'skin', 2.99, 4.5, 0, '👁️', '{"primary":"#991B1B","secondary":"#000000","bg":"#000000","accent":"#DC2626"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#991B1B"},"background":{"type":"animated_gradient","colors":["#000000","#0A0A0A","#991B1B10"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#991B1B30","speed":0.3}},"focus_highlight":{"type":"glow","color":"#991B1B","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#991B1B","progress_bar":"#991B1B","buffer_color":"#000000"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('perfect-illusion', 'Perfect Illusion (Inspired)', 'KuroStream Studio', 'White, purple and gold with elegant luxury design and illusion-like animations. High-class interface inspired by master illusionist characters.', 'White, purple and gold with elegant luxury design and illusion-like animations. High-class interface inspired by master illusionist characters.', 'skin', 2.99, 4.5, 0, '✨', '{"primary":"#FFFFFF","secondary":"#8B5CF6","bg":"#0A0A0F","accent":"#F59E0B"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#FFFFFF"},"background":{"type":"animated_gradient","colors":["#0A0A0F","#151520","#FFFFFF10"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#8B5CF630","speed":0.3}},"focus_highlight":{"type":"glow","color":"#8B5CF6","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#FFFFFF","progress_bar":"#FFFFFF","buffer_color":"#8B5CF6"}}', 1, '#', '[]', 'approved', 'system', 'Original inspired design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('midnight-blue', 'Midnight Blue', 'KuroStream Studio', 'Clean dark blue theme with subtle gradients. Perfect for late-night viewing.', 'Clean dark blue theme with subtle gradients. Perfect for late-night viewing.', 'skin', 0, 4.5, 0, '🌌', '{"primary":"#3B82F6","secondary":"#60A5FA","bg":"#000000","accent":"#60A5FA"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#3B82F6"},"background":{"type":"animated_gradient","colors":["#000000","#0A0A15","#3B82F610"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#3B82F630","speed":0.3}},"focus_highlight":{"type":"glow","color":"#3B82F6","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#3B82F6","progress_bar":"#3B82F6","buffer_color":"#60A5FA"}}', 0, '#', '[]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('forest-green', 'Forest Green', 'KuroStream Studio', 'Calming green tones inspired by nature. Easy on the eyes for long sessions.', 'Calming green tones inspired by nature. Easy on the eyes for long sessions.', 'skin', 0, 4.5, 0, '🌲', '{"primary":"#22C55E","secondary":"#4ADE80","bg":"#000A00","accent":"#4ADE80"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#22C55E"},"background":{"type":"animated_gradient","colors":["#000A00","#0A150A","#22C55E10"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#22C55E30","speed":0.3}},"focus_highlight":{"type":"glow","color":"#22C55E","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#22C55E","progress_bar":"#22C55E","buffer_color":"#4ADE80"}}', 0, '#', '[]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('sunset-orange', 'Sunset Orange', 'KuroStream Studio', 'Warm orange and amber tones reminiscent of a beautiful sunset.', 'Warm orange and amber tones reminiscent of a beautiful sunset.', 'skin', 0, 4.5, 0, '🌇', '{"primary":"#F97316","secondary":"#FB923C","bg":"#0A0500","accent":"#FB923C"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#F97316"},"background":{"type":"animated_gradient","colors":["#0A0500","#1A1005","#F9731610"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#F9731630","speed":0.3}},"focus_highlight":{"type":"glow","color":"#F97316","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#F97316","progress_bar":"#F97316","buffer_color":"#FB923C"}}', 0, '#', '[]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('crystal-clear', 'Crystal Clear', 'KuroStream Studio', 'Ultra-minimal grey and white theme with maximum clarity and zero distractions.', 'Ultra-minimal grey and white theme with maximum clarity and zero distractions.', 'skin', 0, 4.5, 0, '💎', '{"primary":"#E5E7EB","secondary":"#9CA3AF","bg":"#0A0A0A","accent":"#E5E7EB"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#E5E7EB"},"background":{"type":"animated_gradient","colors":["#0A0A0A","#141414","#E5E7EB10"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#9CA3AF30","speed":0.3}},"focus_highlight":{"type":"glow","color":"#9CA3AF","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#E5E7EB","progress_bar":"#E5E7EB","buffer_color":"#9CA3AF"}}', 0, '#', '[]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now')),
('neon-cyberpunk', 'Neon Cyberpunk', 'KuroStream Studio', 'Vibrant neon pink and cyan on pure black. Cyberpunk aesthetic for the modern viewer.', 'Vibrant neon pink and cyan on pure black. Cyberpunk aesthetic for the modern viewer.', 'skin', 0, 4.5, 0, '🌆', '{"primary":"#D946EF","secondary":"#06B6D4","bg":"#000000","accent":"#06B6D4"}', '{"glass_cards":{"enabled":true,"opacity":0.88,"blur_radius":16,"border_width":1.5,"border_alpha":0.2,"border_color":"#D946EF"},"background":{"type":"animated_gradient","colors":["#000000","#0A0A15","#D946EF10"],"animation_speed":0.5,"particle_system":{"enabled":true,"type":"ambient","count":40,"color":"#D946EF30","speed":0.3}},"focus_highlight":{"type":"glow","color":"#D946EF","width":3,"radius":12,"alpha":0.7,"animation":"pulse"},"transitions":{"type":"cinematic","duration":400,"easing":"ease_out_cubic"},"player_overlay":{"background":"#000000E6","accent":"#D946EF","progress_bar":"#D946EF","buffer_color":"#06B6D4"}}', 0, '#', '[]', 'approved', 'system', 'Original design', 'system', datetime('now'), NULL, datetime('now'), datetime('now'));
